# Generated by Django 6.0.1 on 2026-01-21 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatterySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество батареек')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сдача батареек',
                'verbose_name_plural': 'Сдачи батареек',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
